import 'dart:isolate';
import 'dart:io';
import 'dart:math' as math;
import 'dart:typed_data';
import 'dart:ui';

import 'package:flutter_svg/flutter_svg.dart';
import 'package:markdown/markdown.dart' as markdown;
import 'package:path_provider/path_provider.dart';
import 'package:syncfusion_flutter_pdf/pdf.dart';

const _pdfMargin = 42.0;
const _svgTextFontFamily = 'QuickLlmPdfSvg';

/// A visual generated by a tool activity that belongs with the chat reply
/// when it is exported. Tool activities are intentionally kept out of the
/// visible reply text, so the caller supplies them separately.
class MarkdownPdfArtifact {
  final String type;
  final String content;
  final String label;

  const MarkdownPdfArtifact({
    required this.type,
    required this.content,
    this.label = 'Generated diagram',
  });
}

/// Exports an assistant reply as a styled, paginated PDF.
///
/// The renderer intentionally handles the Markdown blocks emitted most often
/// by chat models: headings, paragraphs, lists, quotes, code blocks, rules,
/// and GitHub-style tables.
class MarkdownPdfService {
  static final PdfColor _ink = PdfColor(31, 41, 55);
  static final PdfColor _muted = PdfColor(100, 116, 139);
  static final PdfColor _teal = PdfColor(13, 148, 136);
  static final PdfColor _softTeal = PdfColor(236, 253, 245);
  static final PdfColor _softCode = PdfColor(241, 245, 249);
  static final PdfColor _line = PdfColor(203, 213, 225);
  List<int>? _regularFontData;
  List<int>? _boldFontData;
  List<int>? _codeFontData;
  List<int>? _svgTextFontData;
  Future<void>? _svgTextFontLoad;

  Future<File> download(
    String source, {
    String title = 'Quick LLM response',
    Directory? outputDirectory,
    void Function(String stage)? onStage,
    Iterable<MarkdownPdfArtifact> artifacts = const <MarkdownPdfArtifact>[],
  }) async {
    final markdownSource = _normalizeMarkdownSource(
      _sourceWithArtifacts(source, artifacts).trim(),
    );
    if (markdownSource.isEmpty) {
      throw const MarkdownPdfException('There is no response to export.');
    }

    final downloadsDirectory = outputDirectory ??
        await getDownloadsDirectory() ??
        await getApplicationDocumentsDirectory();
    if (!await downloadsDirectory.exists()) {
      await downloadsDirectory.create(recursive: true);
    }

    onStage?.call('Preparing PDF');
    // Give the download button time to repaint its progress state before any
    // synchronous PDF work begins.
    await Future<void>.delayed(Duration.zero);

    final containsVisualDiagram = _containsVisualDiagram(markdownSource);
    final List<int> bytes;
    if (containsVisualDiagram) {
      onStage?.call('Rendering diagrams');
      await _loadFonts();
      bytes = await _buildPdfBytes(markdownSource, title);
    } else {
      onStage?.call('Formatting response');
      bytes = await Isolate.run(
        () => _buildTextOnlyPdfInBackground(markdownSource, title),
      );
    }

    onStage?.call('Saving PDF');
    final destination = File(
      '${downloadsDirectory.path}${Platform.pathSeparator}'
      'quick_llm_${DateTime.now().microsecondsSinceEpoch}.pdf',
    );
    return destination.writeAsBytes(bytes, flush: true);
  }

  Future<List<int>> _buildPdfBytes(String source, String title) async {
    final document = PdfDocument()
      ..pageSettings.margins = (PdfMargins()..all = _pdfMargin);
    try {
      _addFooter(document);
      final cursor = _PdfCursor(document, document.pages.add());
      _drawTitle(cursor, title);

      await _drawMarkdownAndSvg(cursor, source);

      return await document.save();
    } finally {
      document.dispose();
    }
  }

  void _addFooter(PdfDocument document) {
    final footer = PdfPageTemplateElement(const Rect.fromLTWH(0, 0, 510, 24));
    footer.graphics.drawLine(
      PdfPen(_line, width: 0.5),
      const Offset(_pdfMargin, 1),
      const Offset(510 - _pdfMargin, 1),
    );
    footer.graphics.drawString(
      'Quick LLM  |  Markdown export',
      _font(8),
      brush: PdfSolidBrush(_muted),
      bounds: const Rect.fromLTWH(_pdfMargin, 7, 220, 12),
    );
    document.template.bottom = footer;
  }

  void _drawTitle(_PdfCursor cursor, String title) {
    _drawText(
      cursor,
      title,
      font: _font(20, bold: true),
      color: _ink,
      bottomSpacing: 4,
    );
    _drawText(
      cursor,
      'Exported ${_formatDate(DateTime.now())}',
      font: _font(8.5),
      color: _muted,
      bottomSpacing: 16,
    );
  }

  /// Renders raw SVG and Mermaid blocks as images rather than letting the
  /// Markdown parser turn their source into a paragraph or code block.
  Future<void> _drawMarkdownAndSvg(_PdfCursor cursor, String source) async {
    final svgPattern = RegExp(r'<svg\b[\s\S]*?</svg>', caseSensitive: false);
    var offset = 0;
    for (final match in svgPattern.allMatches(source)) {
      await _drawMarkdown(cursor, source.substring(offset, match.start));
      await _drawSvg(cursor, match.group(0)!);
      offset = match.end;
    }
    await _drawMarkdown(cursor, source.substring(offset));
  }

  Future<void> _drawMarkdown(_PdfCursor cursor, String source) async {
    if (source.trim().isEmpty) return;
    final nodes = markdown.Document(
      extensionSet: markdown.ExtensionSet.gitHubFlavored,
    ).parse(source);
    for (final node in nodes) {
      if (node is markdown.Element) {
        await _drawBlock(cursor, node);
      } else if (node.textContent.trim().isNotEmpty) {
        _drawParagraph(cursor, node.textContent);
      }
    }
  }

  Future<void> _drawSvg(
    _PdfCursor cursor,
    String svg, {
    bool allowFallback = true,
  }) async {
    PictureInfo? pictureInfo;
    Picture? scaledPicture;
    Image? image;
    try {
      try {
        await _loadSvgTextFont();
      } catch (_) {
        // The SVG still has a platform fallback if a local text font cannot
        // be registered on this device.
      }
      pictureInfo = await vg.loadPicture(
        SvgStringLoader(_svgForPdf(svg)),
        null,
      );
      final sourceSize = pictureInfo.size;
      final sourceWidth = sourceSize.width > 0 ? sourceSize.width : 4.0;
      final sourceHeight = sourceSize.height > 0 ? sourceSize.height : 3.0;
      final aspectRatio = sourceWidth / sourceHeight;
      final svgLabels = _svgLabels(svg);
      if (allowFallback && aspectRatio > 4.5 && svgLabels.length > 1) {
        // A one-row process map with many cards only fits on a PDF page by
        // shrinking it until the labels are unreadable. Reflow the labels into
        // a compact PDF diagram so every card remains whole and legible.
        await _drawSvg(
          cursor,
          _diagramGridSvg('Generated diagram', svgLabels),
          allowFallback: false,
        );
        return;
      }

      var targetWidth = cursor.width;
      var targetHeight = targetWidth / aspectRatio;
      // Keep a complete diagram on one PDF page. The former minimum-height
      // logic could expand very wide diagrams past the right edge of the page,
      // which made them look as though half the graphic had been cut away.
      if (targetHeight > 460) {
        targetHeight = 460;
        targetWidth = targetHeight * aspectRatio;
      }
      // SVGs are vector input, but PDFs receive a raster image. Render at a
      // higher density so chart labels and fine lines stay crisp after export.
      final pixelWidth = (targetWidth * 4).round().clamp(1, 8192).toInt();
      final pixelHeight = (targetHeight * 4).round().clamp(1, 4096).toInt();
      final recorder = PictureRecorder();
      Canvas(recorder)
        ..scale(pixelWidth / sourceWidth, pixelHeight / sourceHeight)
        ..drawPicture(pictureInfo.picture);
      scaledPicture = recorder.endRecording();
      image = await scaledPicture.toImage(pixelWidth, pixelHeight);
      final png = await image.toByteData(format: ImageByteFormat.png);
      if (png == null) throw StateError('The SVG could not be encoded.');

      cursor.ensureSpace(targetHeight + 12);
      cursor.page.graphics.drawImage(
        PdfBitmap(png.buffer.asUint8List()),
        Rect.fromLTWH(_pdfMargin, cursor.y, targetWidth, targetHeight),
      );
      cursor.y += targetHeight + 12;
    } catch (_) {
      if (allowFallback) {
        // A model can return SVG features Flutter does not implement. Rather
        // than show an error in the PDF, retain the diagram's visible labels
        // in a safe, native SVG layout.
        await _drawSvg(
          cursor,
          _svgFallback(svg),
          allowFallback: false,
        );
        return;
      }
      _drawBoxedText(
        cursor,
        'SVG graphic could not be rendered.',
        background: PdfColor(255, 247, 237),
        textColor: _ink,
        font: _font(10),
        bottomSpacing: 10,
      );
    } finally {
      image?.dispose();
      scaledPicture?.dispose();
      pictureInfo?.picture.dispose();
    }
  }

  String _sourceWithArtifacts(
    String source,
    Iterable<MarkdownPdfArtifact> artifacts,
  ) {
    final sections = <String>[source.trim()];
    var combined = source;
    for (final artifact in artifacts) {
      final type = artifact.type.trim().toLowerCase();
      final content = artifact.content.trim();
      if (content.isEmpty || (type != 'svg' && type != 'mermaid')) continue;
      if (combined.contains(content)) continue;

      final label = artifact.label.trim().isEmpty
          ? 'Generated diagram'
          : artifact.label.trim();
      final visual = type == 'mermaid'
          ? '```mermaid\n$content\n```'
          : _svgFromArtifact(content);
      sections.add('## $label\n\n$visual');
      combined = '$combined\n$visual';
    }
    return sections.where((section) => section.trim().isNotEmpty).join('\n\n');
  }

  String _svgFromArtifact(String content) {
    final match = RegExp(r'<svg\b[\s\S]*?</svg>', caseSensitive: false)
        .firstMatch(content);
    return match?.group(0) ?? content;
  }

  String _svgFallback(String source) {
    return _diagramGridSvg('Generated diagram', _svgLabels(source));
  }

  List<String> _svgLabels(String source) {
    final labels = <String>[];
    for (final match in RegExp(
      r'<text\b[^>]*>([\s\S]*?)</text>',
      caseSensitive: false,
    ).allMatches(source)) {
      final label = _cleanMermaidDiagramLabel(
        match.group(1)!.replaceAll(RegExp(r'<[^>]+>'), ' '),
      );
      if (label.isNotEmpty && !labels.contains(label) && labels.length < 12) {
        labels.add(label);
      }
    }
    return labels;
  }

  String _diagramGridSvg(String title, List<String> sourceLabels) {
    final labels = sourceLabels
        .map(_cleanMermaidDiagramLabel)
        .where((label) => label.isNotEmpty)
        .take(12)
        .toList();
    if (labels.isEmpty) labels.add('Diagram');

    const width = 760.0;
    const edgeInset = 24.0;
    const gap = 20.0;
    const nodeHeight = 58.0;
    const rowSpacing = 100.0;
    final columns = math.min(4, labels.length).toInt();
    final rows = (labels.length / columns).ceil();
    final nodeWidth = (width - edgeInset * 2 - gap * (columns - 1)) / columns;
    final height = 72 + rows * rowSpacing;
    final positions = <Offset>[
      for (var index = 0; index < labels.length; index++)
        Offset(
          edgeInset + (index % columns) * (nodeWidth + gap),
          52 + (index ~/ columns) * rowSpacing,
        ),
    ];
    String n(num value) => value.toStringAsFixed(1);
    final buffer = StringBuffer()
      ..writeln(
          '<svg xmlns="http://www.w3.org/2000/svg" width="${n(width)}" height="${n(height)}" viewBox="0 0 ${n(width)} ${n(height)}">')
      ..writeln(
          '<rect width="${n(width)}" height="${n(height)}" rx="12" fill="#f8fafc"/>')
      ..writeln(
          '<text x="20" y="28" fill="#0f766e" font-size="14" font-weight="700">${_escapeSvgText(title)}</text>');

    for (var index = 0; index < positions.length - 1; index++) {
      final from = positions[index];
      final to = positions[index + 1];
      final sameRow = index ~/ columns == (index + 1) ~/ columns;
      final x1 = sameRow ? from.dx + nodeWidth : from.dx + nodeWidth / 2;
      final y1 = sameRow ? from.dy + nodeHeight / 2 : from.dy + nodeHeight;
      final x2 = sameRow ? to.dx : to.dx + nodeWidth / 2;
      final y2 = sameRow ? to.dy + nodeHeight / 2 : to.dy;
      buffer.writeln(
          '<line x1="${n(x1)}" y1="${n(y1)}" x2="${n(x2)}" y2="${n(y2)}" stroke="#64748b" stroke-width="1.8"/>');
      if (sameRow) {
        buffer.writeln(
            '<polygon points="${n(x2)},${n(y2)} ${n(x2 - 8)},${n(y2 - 4.5)} ${n(x2 - 8)},${n(y2 + 4.5)}" fill="#64748b"/>');
      } else {
        buffer.writeln(
            '<polygon points="${n(x2)},${n(y2)} ${n(x2 - 4.5)},${n(y2 - 8)} ${n(x2 + 4.5)},${n(y2 - 8)}" fill="#64748b"/>');
      }
    }
    for (var index = 0; index < positions.length; index++) {
      final position = positions[index];
      final fill = index == 0 ? '#ccfbf1' : '#ffffff';
      buffer
        ..writeln(
            '<rect x="${n(position.dx)}" y="${n(position.dy)}" width="${n(nodeWidth)}" height="$nodeHeight" rx="8" fill="$fill" stroke="#0f766e" stroke-width="1.5"/>')
        ..write(_diagramLabelSvg(
          labels[index],
          position.dx + nodeWidth / 2,
          position.dy + nodeHeight / 2,
        ));
    }
    buffer.writeln('</svg>');
    return buffer.toString();
  }

  bool _containsVisualDiagram(String source) {
    if (RegExp(r'<svg\b[\s\S]*?</svg>', caseSensitive: false)
        .hasMatch(source)) {
      return true;
    }
    if (RegExp(r'^\s*```\s*mermaid(?:\s|$)',
            multiLine: true, caseSensitive: false)
        .hasMatch(source)) {
      return true;
    }
    return RegExp(
      r'^\s*```[^\r\n]*\r?\n\s*'
      r'(?:flowchart|graph\s|mindmap|sequenceDiagram|classDiagram|'
      r'stateDiagram(?:-v2)?|erDiagram|xychart(?:-beta)?|pie)\b',
      multiLine: true,
      caseSensitive: false,
    ).hasMatch(source);
  }

  bool _isMermaidDiagram(markdown.Element pre, String source) {
    if (_codeFenceLanguage(pre) == 'mermaid') return true;
    return _looksLikeMermaidDiagram(source);
  }

  bool _looksLikeMermaidDiagram(String source) {
    final normalized = _normalizeMermaidSource(source);
    return RegExp(
      r'^\s*(?:flowchart|graph\s+|mindmap|sequenceDiagram|classDiagram|'
      r'stateDiagram(?:-v2)?|erDiagram|xychart(?:-beta)?|pie)\b',
      caseSensitive: false,
    ).hasMatch(normalized);
  }

  Future<void> _drawMermaidDiagram(
    _PdfCursor cursor,
    String source,
  ) async {
    // Mermaid is not a PDF format. Convert the safely recognized subset to
    // SVG first, then use the same raster path as tool-generated SVG charts.
    // This guarantees that a Mermaid block never falls back to raw code in an
    // exported document.
    await _drawSvg(cursor, _mermaidSvg(source));
  }

  String _mermaidSvg(String source) {
    final normalized = _normalizeMermaidSource(source);
    final lower = normalized.toLowerCase();
    final title = _mermaidDiagramTitle(lower);

    if (lower.startsWith('flowchart') || lower.startsWith('graph ')) {
      final labels = <String, String>{};
      final orderedIds = <String>[];
      final edges = <_MermaidEdge>[];

      void addNode(String id, [String? label]) {
        final cleanId = id.trim();
        if (cleanId.isEmpty) return;
        if (!orderedIds.contains(cleanId)) orderedIds.add(cleanId);
        if (label != null) {
          final cleanLabel = _cleanMermaidDiagramLabel(label);
          if (cleanLabel.isNotEmpty) labels[cleanId] = cleanLabel;
        } else {
          labels.putIfAbsent(cleanId, () => cleanId);
        }
      }

      final nodePattern = RegExp(
        r'([A-Za-z][A-Za-z0-9_-]*)\s*'
        r'(?:\["([^"\]]+)"\]|\[([^\]]+)\]|\("([^"]+)"\)|'
        r'\(([^)]+)\)|\{([^}]+)\})',
      );
      for (final match in nodePattern.allMatches(normalized)) {
        addNode(
          match.group(1)!,
          match.group(2) ??
              match.group(3) ??
              match.group(4) ??
              match.group(5) ??
              match.group(6),
        );
      }

      // Providers often HTML-escape arrows or leave a space before `>`. The
      // source normalizer has decoded entities; this makes the remaining arrow
      // variants agree with Mermaid's regular `-->` form.
      final repairedArrows = normalized.replaceAllMapped(
        RegExp(r'(?:-+|=+|\.\-)\s*>'),
        (_) => '-->',
      );
      final edgePattern = RegExp(
        r'([A-Za-z][A-Za-z0-9_-]*)\s*'
        r'(?:-->(?:\|[^|]*\|)?|-\.->|==>)\s*'
        r'([A-Za-z][A-Za-z0-9_-]*)',
      );
      for (final match in edgePattern.allMatches(repairedArrows)) {
        final from = match.group(1)!;
        final to = match.group(2)!;
        addNode(from);
        addNode(to);
        if (!edges.any((edge) => edge.from == from && edge.to == to)) {
          edges.add(_MermaidEdge(from, to));
        }
      }

      if (orderedIds.isNotEmpty) {
        final direction = RegExp(
          r'^(?:flowchart|graph)\s+(LR|RL|TD|TB|BT)\b',
          caseSensitive: false,
        ).firstMatch(normalized)?.group(1)?.toUpperCase();
        return _diagramSvg(
          title,
          orderedIds,
          labels,
          edges,
          horizontal: direction == 'LR' || direction == 'RL',
        );
      }
    }

    final labels = _extractMermaidDiagramLabels(normalized);
    final ids = <String>[
      for (var index = 0; index < labels.length; index++) 'node$index',
    ];
    final nodeLabels = <String, String>{
      for (var index = 0; index < labels.length; index++)
        ids[index]: labels[index],
    };
    final edges = <_MermaidEdge>[
      for (var index = 1; index < ids.length; index++)
        _MermaidEdge(ids[index - 1], ids[index]),
    ];
    return _diagramSvg(title, ids, nodeLabels, edges, horizontal: true);
  }

  String _normalizeMermaidSource(String source) {
    return _decodeHtmlEntities(source)
        .replaceAll(r'\"', '"')
        .replaceAll(r"\'", "'")
        .replaceAll(r'\/', '/')
        .replaceAll('\r\n', '\n')
        .replaceAll('\r', '\n')
        .trim();
  }

  String _mermaidDiagramTitle(String lowerSource) {
    if (lowerSource.startsWith('mindmap')) return 'Mind map';
    if (lowerSource.startsWith('sequence')) return 'Sequence diagram';
    if (lowerSource.startsWith('class')) return 'Class diagram';
    if (lowerSource.startsWith('state')) return 'State diagram';
    if (lowerSource.startsWith('er')) return 'Entity relationship diagram';
    if (lowerSource.startsWith('xychart')) return 'Chart';
    if (lowerSource.startsWith('pie')) return 'Pie chart';
    return 'Flowchart';
  }

  List<String> _extractMermaidDiagramLabels(String source) {
    final labels = <String>[];
    void add(String? value) {
      final clean = _cleanMermaidDiagramLabel(value ?? '');
      if (clean.isNotEmpty && !labels.contains(clean) && labels.length < 12) {
        labels.add(clean);
      }
    }

    for (final rawLine in source.split('\n')) {
      final line = rawLine.trim();
      if (line.isEmpty || line.startsWith('%%')) continue;
      if (RegExp(
        r'^(?:mindmap|sequenceDiagram|classDiagram|stateDiagram(?:-v2)?|'
        r'erDiagram|xychart(?:-beta)?|pie)\b',
        caseSensitive: false,
      ).hasMatch(line)) {
        continue;
      }

      final declaration = RegExp(
        r'^(?:participant|actor|class|state|entity)\s+([^\s{]+)(?:\s+as\s+(.+))?',
        caseSensitive: false,
      ).firstMatch(line);
      if (declaration != null) {
        add(declaration.group(2) ?? declaration.group(1));
        continue;
      }

      final quoted = RegExp(r'''["']([^"']+)["']''').allMatches(line);
      for (final match in quoted) {
        add(match.group(1));
      }

      final edge = RegExp(
        r'^([A-Za-z][A-Za-z0-9_-]*)\s*(?:-->|->>|-->>|--|==>|<--|[|}{o]+--[|}{o]+)\s*([A-Za-z][A-Za-z0-9_-]*)',
      ).firstMatch(line);
      if (edge != null) {
        add(edge.group(1));
        add(edge.group(2));
        continue;
      }

      final axis = RegExp(r'^(?:x-axis|y-axis|bar|line)\s*\[([^\]]+)\]',
              caseSensitive: false)
          .firstMatch(line);
      if (axis != null) {
        for (final value in axis.group(1)!.split(',')) {
          if (double.tryParse(value.trim()) == null) add(value);
        }
        continue;
      }

      final mindMapLine = line
          .replaceAll(RegExp(r'^[-*]+\s*'), '')
          .replaceAll(RegExp(r'^(?:root\s*)?\(\('), '')
          .replaceAll(RegExp(r'\)\)$'), '')
          .trim();
      if (mindMapLine.isNotEmpty) add(mindMapLine);
    }

    return labels.isEmpty ? const ['Diagram'] : labels;
  }

  String _cleanMermaidDiagramLabel(String value) {
    return _decodeHtmlEntities(value)
        .replaceAll(
          RegExp(r'''^[\[\]{}()\s"']+|[\[\]{}()\s"']+$'''),
          '',
        )
        .replaceAll(RegExp(r'\s+'), ' ')
        .trim();
  }

  String _diagramSvg(
    String title,
    List<String> ids,
    Map<String, String> labels,
    List<_MermaidEdge> edges, {
    required bool horizontal,
  }) {
    final visibleIds = ids.take(18).toList();
    if (visibleIds.isEmpty) visibleIds.add('diagram');
    final visible = visibleIds.toSet();
    final visibleEdges = edges
        .where(
            (edge) => visible.contains(edge.from) && visible.contains(edge.to))
        .toList();
    final incoming = <String, List<String>>{
      for (final id in visibleIds) id: <String>[],
    };
    for (final edge in visibleEdges) {
      incoming[edge.to]!.add(edge.from);
    }
    final levels = <String, int>{};
    int levelFor(String id, Set<String> path) {
      final cached = levels[id];
      if (cached != null) return cached;
      if (!path.add(id)) return 0;
      var level = 0;
      for (final parent in incoming[id] ?? const <String>[]) {
        level = math.max(level, levelFor(parent, path) + 1);
      }
      path.remove(id);
      return levels[id] = level;
    }

    for (final id in visibleIds) {
      levelFor(id, <String>{});
    }
    final groups = <int, List<String>>{};
    for (final id in visibleIds) {
      groups.putIfAbsent(levels[id]!, () => <String>[]).add(id);
    }
    final maxLevel = groups.keys.fold<int>(0, math.max);
    final maxPerLevel = groups.values
        .fold<int>(1, (maximum, group) => math.max(maximum, group.length));
    const nodeWidth = 152.0;
    const nodeHeight = 54.0;
    const laneSpacing = 92.0;
    final width = horizontal
        ? math.max(760.0, 120 + (maxLevel + 1) * 190.0)
        : math.max(760.0, 100 + maxPerLevel * 178.0);
    final height = horizontal
        ? math.max(190.0, 82 + maxPerLevel * laneSpacing + 54)
        : math.max(190.0, 82 + (maxLevel + 1) * 110.0 + 24);
    final positions = <String, Offset>{};
    for (final entry in groups.entries) {
      final group = entry.value;
      for (var index = 0; index < group.length; index++) {
        final x = horizontal
            ? 42 + entry.key * 190.0
            : (width - group.length * nodeWidth) / 2 + index * nodeWidth;
        final y =
            horizontal ? 58 + index * laneSpacing : 54 + entry.key * 110.0;
        positions[group[index]] = Offset(x, y);
      }
    }

    String n(num value) => value.toStringAsFixed(1);
    final buffer = StringBuffer()
      ..writeln(
          '<svg xmlns="http://www.w3.org/2000/svg" width="${n(width)}" height="${n(height)}" viewBox="0 0 ${n(width)} ${n(height)}">')
      ..writeln(
          '<rect width="${n(width)}" height="${n(height)}" rx="12" fill="#f8fafc"/>')
      ..writeln(
          '<text x="20" y="28" fill="#0f766e" font-size="14" font-weight="700">${_escapeSvgText(title)}</text>');
    for (final edge in visibleEdges) {
      final from = positions[edge.from]!;
      final to = positions[edge.to]!;
      final x1 = horizontal ? from.dx + nodeWidth : from.dx + nodeWidth / 2;
      final y1 = horizontal ? from.dy + nodeHeight / 2 : from.dy + nodeHeight;
      final x2 = horizontal ? to.dx : to.dx + nodeWidth / 2;
      final y2 = horizontal ? to.dy + nodeHeight / 2 : to.dy;
      buffer.writeln(
          '<line x1="${n(x1)}" y1="${n(y1)}" x2="${n(x2)}" y2="${n(y2)}" stroke="#64748b" stroke-width="1.8"/>');
      if (horizontal) {
        final direction = x2 >= x1 ? 1.0 : -1.0;
        buffer.writeln(
            '<polygon points="${n(x2)},${n(y2)} ${n(x2 - direction * 8)},${n(y2 - 4.5)} ${n(x2 - direction * 8)},${n(y2 + 4.5)}" fill="#64748b"/>');
      } else {
        final direction = y2 >= y1 ? 1.0 : -1.0;
        buffer.writeln(
            '<polygon points="${n(x2)},${n(y2)} ${n(x2 - 4.5)},${n(y2 - direction * 8)} ${n(x2 + 4.5)},${n(y2 - direction * 8)}" fill="#64748b"/>');
      }
    }
    for (final id in visibleIds) {
      final position = positions[id]!;
      final label = labels[id] ?? id;
      final isRoot = (incoming[id] ?? const <String>[]).isEmpty;
      final fill = isRoot ? '#ccfbf1' : '#ffffff';
      buffer
        ..writeln(
            '<rect x="${n(position.dx)}" y="${n(position.dy)}" width="$nodeWidth" height="$nodeHeight" rx="8" fill="$fill" stroke="#0f766e" stroke-width="1.5"/>')
        ..write(_diagramLabelSvg(
            label, position.dx + nodeWidth / 2, position.dy + nodeHeight / 2));
    }
    buffer.writeln('</svg>');
    return buffer.toString();
  }

  String _diagramLabelSvg(String label, double centerX, double centerY) {
    final lines = _wrapDiagramLabel(label);
    final startY = centerY - (lines.length - 1) * 7.5;
    final buffer = StringBuffer(
      '<text x="${centerX.toStringAsFixed(1)}" y="${startY.toStringAsFixed(1)}" text-anchor="middle" dominant-baseline="middle" fill="#0f172a" font-size="11.5" font-weight="600">',
    );
    for (var index = 0; index < lines.length; index++) {
      buffer.write(
          '<tspan x="${centerX.toStringAsFixed(1)}" dy="${index == 0 ? 0 : 15}">${_escapeSvgText(lines[index])}</tspan>');
    }
    return '${buffer.toString()}</text>\n';
  }

  List<String> _wrapDiagramLabel(String value) {
    final words = _cleanMermaidDiagramLabel(value).split(RegExp(r'\s+'));
    final lines = <String>[];
    var line = '';
    for (final word in words) {
      final next = line.isEmpty ? word : '$line $word';
      if (next.length <= 21 || line.isEmpty) {
        line = next;
      } else {
        lines.add(line);
        line = word;
      }
      if (lines.length == 2) break;
    }
    if (line.isNotEmpty && lines.length < 2) lines.add(line);
    if (lines.isEmpty) return const ['Diagram'];
    if (words.join(' ').length > lines.join(' ').length) {
      final last = lines.length - 1;
      lines[last] =
          '${lines[last].substring(0, math.min(18, lines[last].length))}…';
    }
    return lines;
  }

  String _escapeSvgText(String value) {
    return value
        .replaceAll('&', '&amp;')
        .replaceAll('<', '&lt;')
        .replaceAll('>', '&gt;')
        .replaceAll('"', '&quot;')
        .replaceAll("'", '&apos;');
  }

  /// SVGs from model responses commonly request desktop fonts such as Arial.
  /// Those fonts are not guaranteed to be available to Flutter's SVG rasterizer
  /// on every desktop, which otherwise displays each label as a missing glyph.
  String _svgForPdf(String svg) {
    var normalized = svg
        // flutter_svg does not implement SVG markers. Local tool mind maps
        // use them for arrowheads, so retain the connector line and remove
        // only the unsupported decoration instead of failing the whole SVG.
        .replaceAll(
          RegExp(r'<marker\b[\s\S]*?</marker>', caseSensitive: false),
          '',
        )
        .replaceAll(
          RegExp(
            r'''\smarker-(?:start|mid|end)\s*=\s*(?:"[^"]*"|'[^']*')''',
            caseSensitive: false,
          ),
          '',
        );

    final viewBox = RegExp(
      r'''\bviewBox\s*=\s*(?:"([^"]+)"|'([^']+)')''',
      caseSensitive: false,
    ).firstMatch(normalized);
    final viewBoxParts = (viewBox?.group(1) ?? viewBox?.group(2) ?? '')
        .split(RegExp(r'[\s,]+'))
        .map(double.tryParse)
        .whereType<double>()
        .toList();
    if (viewBoxParts.length == 4) {
      final width = viewBoxParts[2];
      final height = viewBoxParts[3];
      normalized = normalized
          .replaceAllMapped(
            RegExp(r'''(\bwidth\s*=\s*)(?:"100%"|'100%')''',
                caseSensitive: false),
            (match) => '${match.group(1)}"$width"',
          )
          .replaceAllMapped(
            RegExp(r'''(\bheight\s*=\s*)(?:"100%"|'100%')''',
                caseSensitive: false),
            (match) => '${match.group(1)}"$height"',
          );
    }

    final withoutDesktopFont = normalized.replaceAll(
      RegExp(r'''\sfont-family\s*=\s*(?:"[^"]*"|'[^']*')''',
          caseSensitive: false),
      '',
    );
    return withoutDesktopFont.replaceAllMapped(
      RegExp(r'<text\b([^>]*)>', caseSensitive: false),
      (match) => '<text${match.group(1)} font-family="$_svgTextFontFamily">',
    );
  }

  Future<void> _drawBlock(_PdfCursor cursor, markdown.Element element) async {
    switch (element.tag) {
      case 'h1':
        _drawHeading(cursor, element.textContent, 18, 14);
      case 'h2':
        _drawHeading(cursor, element.textContent, 15, 12);
      case 'h3':
        _drawHeading(cursor, element.textContent, 13, 10);
      case 'h4':
      case 'h5':
      case 'h6':
        _drawHeading(cursor, element.textContent, 11, 8);
      case 'p':
        final source = element.textContent;
        if (_looksLikeMermaidDiagram(source)) {
          await _drawMermaidDiagram(cursor, source);
        } else {
          _drawParagraphElement(cursor, element);
        }
      case 'ul':
        _drawList(cursor, element, ordered: false);
      case 'ol':
        _drawList(cursor, element, ordered: true);
      case 'blockquote':
        _drawQuote(cursor, element.textContent);
      case 'pre':
        final source = element.textContent;
        if (_isMermaidDiagram(element, source)) {
          await _drawMermaidDiagram(cursor, source);
        } else if (_shouldRenderCodeBlockAsMarkdown(element, source)) {
          await _drawMarkdown(cursor, source);
        } else {
          _drawCode(cursor, source);
        }
      case 'table':
        _drawTable(cursor, element);
      case 'hr':
        _drawRule(cursor);
      case 'img':
        _drawParagraph(
            cursor, '[Image: ${element.attributes['alt'] ?? 'image'}]');
      default:
        final text = element.textContent.trim();
        if (text.isNotEmpty) _drawParagraph(cursor, text);
    }
  }

  void _drawHeading(
    _PdfCursor cursor,
    String text,
    double size,
    double spacing,
  ) {
    _drawText(
      cursor,
      _cleanText(text),
      font: _font(size, bold: true),
      color: _teal,
      topSpacing: 4,
      bottomSpacing: spacing,
    );
  }

  void _drawParagraph(_PdfCursor cursor, String text) {
    final clean = _cleanText(text);
    if (clean.isEmpty) return;
    _drawRichText(
      cursor,
      <_PdfInlineText>[_PdfInlineText(clean)],
      bottomSpacing: 9,
    );
  }

  void _drawParagraphElement(
    _PdfCursor cursor,
    markdown.Element element,
  ) {
    final spans = _inlineText(element);
    if (spans.isEmpty) return;
    _drawRichText(cursor, spans, bottomSpacing: 9);
  }

  List<_PdfInlineText> _inlineText(
    markdown.Node node, {
    bool bold = false,
  }) {
    if (node is markdown.Text) {
      final text = _sanitizeExportText(node.text);
      return text.isEmpty
          ? const <_PdfInlineText>[]
          : <_PdfInlineText>[_PdfInlineText(text, bold: bold)];
    }
    if (node is! markdown.Element) return const <_PdfInlineText>[];

    final isBold = bold || node.tag == 'strong';
    return <_PdfInlineText>[
      for (final child in node.children ?? const <markdown.Node>[])
        ..._inlineText(child, bold: isBold),
    ];
  }

  void _drawRichText(
    _PdfCursor cursor,
    List<_PdfInlineText> spans, {
    required double bottomSpacing,
    double leftInset = 0,
  }) {
    const fontSize = 10.5;
    const lineHeight = 15.0;
    final startX = _pdfMargin + leftInset;
    final rightX = _pdfMargin + cursor.width;
    var x = startX;

    void nextLine() {
      cursor.y += lineHeight;
      cursor.ensureSpace(lineHeight);
      x = startX;
    }

    cursor.ensureSpace(lineHeight);
    for (final span in spans) {
      final font = _font(fontSize, bold: span.bold);
      final lines = span.text.split('\n');
      for (var lineIndex = 0; lineIndex < lines.length; lineIndex++) {
        final line = lines[lineIndex];
        for (final tokenMatch in RegExp(r'\S+|\s+').allMatches(line)) {
          final token = tokenMatch.group(0)!;
          final isWhitespace = token.trim().isEmpty;
          if (x == startX && isWhitespace) continue;
          final tokenWidth = font
              .measureString(
                _pdfSafeText(token),
                format: PdfStringFormat(measureTrailingSpaces: true),
              )
              .width;
          if (isWhitespace) {
            if (x + tokenWidth <= rightX) x += tokenWidth;
            continue;
          }
          if (x > startX && x + tokenWidth > rightX) nextLine();

          cursor.page.graphics.drawString(
            _pdfSafeText(token),
            font,
            brush: PdfSolidBrush(_ink),
            bounds: Rect.fromLTWH(x, cursor.y, rightX - x, lineHeight),
          );
          x += tokenWidth;
        }
        if (lineIndex < lines.length - 1) nextLine();
      }
    }
    cursor.y += lineHeight + bottomSpacing;
    cursor.ensureSpace(1);
  }

  void _drawList(
    _PdfCursor cursor,
    markdown.Element list, {
    required bool ordered,
  }) {
    final items = (list.children ?? const <markdown.Node>[])
        .whereType<markdown.Element>()
        .where((item) => item.tag == 'li')
        .toList();
    for (var index = 0; index < items.length; index++) {
      final marker = ordered ? '${index + 1}.' : '-';
      _drawText(
        cursor,
        '$marker ${_cleanText(items[index].textContent)}',
        font: _font(10.5),
        color: _ink,
        leftInset: 12,
        bottomSpacing: 5,
      );
    }
    cursor.y += 4;
  }

  void _drawQuote(_PdfCursor cursor, String text) {
    _drawBoxedText(
      cursor,
      _cleanText(text),
      background: _softTeal,
      textColor: _ink,
      font: _font(10.5),
      bottomSpacing: 10,
    );
  }

  void _drawCode(_PdfCursor cursor, String text) {
    final chunks = _chunkCodeBlock(text.trimRight());
    for (var index = 0; index < chunks.length; index++) {
      _drawBoxedText(
        cursor,
        chunks[index],
        background: _softCode,
        textColor: _ink,
        font: _font(8.5, monospace: true),
        bottomSpacing: index == chunks.length - 1 ? 11 : 3,
        hardWrap: true,
        borderColor: _line,
      );
    }
  }

  /// Splits code into small, bounded layout units before handing it to
  /// [PdfGrid]. A single very long YAML value can otherwise make the PDF
  /// layout engine repeatedly measure one enormous table cell.
  List<String> _chunkCodeBlock(String source) {
    if (source.isEmpty) return const <String>[];

    // Keep each grid cell substantially smaller than a page. This both bounds
    // work for pathological scalar values and lets a code block continue on
    // the same page as the heading that introduces it.
    const maxCharactersPerVisualLine = 70;
    const maxVisualLinesPerChunk = 16;
    final visualLines = <String>[];

    for (final line in source.split('\n')) {
      if (line.isEmpty) {
        visualLines.add('');
        continue;
      }

      var start = 0;
      while (start < line.length) {
        var end = math.min(start + maxCharactersPerVisualLine, line.length);
        // Do not split a Unicode surrogate pair while hard-wrapping a long
        // scalar value. YAML is usually ASCII, but generated data can contain
        // emoji and other supplementary characters.
        if (end < line.length &&
            end > start &&
            line.codeUnitAt(end) >= 0xDC00 &&
            line.codeUnitAt(end) <= 0xDFFF) {
          end--;
        }
        if (end == start) end = math.min(start + 2, line.length);
        visualLines.add(line.substring(start, end));
        start = end;
      }
    }

    return <String>[
      for (var start = 0;
          start < visualLines.length;
          start += maxVisualLinesPerChunk)
        visualLines
            .sublist(
              start,
              math.min(start + maxVisualLinesPerChunk, visualLines.length),
            )
            .join('\n'),
    ];
  }

  void _drawRule(_PdfCursor cursor) {
    cursor.ensureSpace(12);
    cursor.page.graphics.drawLine(
      PdfPen(_line, width: 0.7),
      Offset(_pdfMargin, cursor.y + 4),
      Offset(_pdfMargin + cursor.width, cursor.y + 4),
    );
    cursor.y += 12;
  }

  void _drawTable(_PdfCursor cursor, markdown.Element table) {
    final rows = _tableRows(table);
    if (rows.isEmpty) return;

    final columnCount = rows.first.length;
    if (columnCount == 0) return;

    final grid = PdfGrid()
      ..repeatHeader = true
      ..style = PdfGridStyle(
        cellPadding: PdfPaddings(left: 6, right: 6, top: 5, bottom: 5),
        font: _font(8.5),
      );
    grid.columns.add(count: columnCount);
    grid.headers.add(1);

    for (var column = 0; column < columnCount; column++) {
      final cell = grid.headers[0].cells[column];
      cell.value = _pdfSafeText(rows.first[column]);
      cell.style = PdfGridCellStyle(
        backgroundBrush: PdfSolidBrush(_teal),
        textBrush: PdfBrushes.white,
        font: _font(8.5, bold: true),
      );
    }

    for (var rowIndex = 1; rowIndex < rows.length; rowIndex++) {
      final row = grid.rows.add();
      for (var column = 0; column < columnCount; column++) {
        final cell = row.cells[column];
        cell.value = _pdfSafeText(rows[rowIndex][column]);
        if (rowIndex.isEven) {
          cell.style = PdfGridCellStyle(
            backgroundBrush: PdfSolidBrush(PdfColor(248, 250, 252)),
          );
        }
      }
    }

    final result = grid.draw(
      page: cursor.page,
      bounds: Rect.fromLTWH(_pdfMargin, cursor.y, cursor.width, 0),
      format: cursor.layoutFormat,
    );
    if (result != null) cursor.updateFrom(result, bottomSpacing: 12);
  }

  List<List<String>> _tableRows(markdown.Element table) {
    final rows = <List<String>>[];
    void collect(markdown.Element element) {
      if (element.tag == 'tr') {
        rows.add(
          (element.children ?? const <markdown.Node>[])
              .whereType<markdown.Element>()
              .where((cell) => cell.tag == 'th' || cell.tag == 'td')
              .map((cell) => _cleanText(cell.textContent))
              .toList(),
        );
        return;
      }
      for (final child in element.children ?? const <markdown.Node>[]) {
        if (child is markdown.Element) collect(child);
      }
    }

    collect(table);
    return rows;
  }

  void _drawBoxedText(
    _PdfCursor cursor,
    String text, {
    required PdfColor background,
    required PdfColor textColor,
    required PdfFont font,
    required double bottomSpacing,
    bool hardWrap = false,
    PdfColor? borderColor,
  }) {
    final grid = PdfGrid()
      ..columns.add(count: 1)
      ..style = PdfGridStyle(
        cellPadding: PdfPaddings(left: 9, right: 9, top: 8, bottom: 8),
      );
    final cell = grid.rows.add().cells[0];
    cell.value = _pdfSafeText(text);
    cell.style = PdfGridCellStyle(
      backgroundBrush: PdfSolidBrush(background),
      textBrush: PdfSolidBrush(textColor),
      font: font,
      format: hardWrap
          ? PdfStringFormat(wordWrap: PdfWordWrapType.character)
          : null,
      borders: borderColor == null
          ? null
          : PdfBorders(
              left: PdfPen(borderColor, width: 0.65),
              top: PdfPen(borderColor, width: 0.65),
              right: PdfPen(borderColor, width: 0.65),
              bottom: PdfPen(borderColor, width: 0.65),
            ),
    );
    final result = grid.draw(
      page: cursor.page,
      bounds: Rect.fromLTWH(_pdfMargin, cursor.y, cursor.width, 0),
      format: cursor.layoutFormat,
    );
    if (result != null) cursor.updateFrom(result, bottomSpacing: bottomSpacing);
  }

  void _drawText(
    _PdfCursor cursor,
    String text, {
    required PdfFont font,
    required PdfColor color,
    double topSpacing = 0,
    double bottomSpacing = 0,
    double leftInset = 0,
  }) {
    cursor.y += topSpacing;
    final element = PdfTextElement(
      text: _pdfSafeText(text),
      font: font,
      brush: PdfSolidBrush(color),
      format: PdfStringFormat(wordWrap: PdfWordWrapType.word),
    );
    final result = element.draw(
      page: cursor.page,
      bounds: Rect.fromLTWH(
        _pdfMargin + leftInset,
        cursor.y,
        cursor.width - leftInset,
        0,
      ),
      format: cursor.layoutFormat,
    );
    if (result != null) cursor.updateFrom(result, bottomSpacing: bottomSpacing);
  }

  Future<void> _loadFonts() async {
    if (_regularFontData != null) return;

    _regularFontData = await _readFirstFont(const [
      r'C:\Windows\Fonts\seguiemj.ttf',
      r'C:\Windows\Fonts\segoeui.ttf',
      '/System/Library/Fonts/Supplemental/Arial Unicode.ttf',
      '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf',
    ]);
    _boldFontData = await _readFirstFont(const [
      r'C:\Windows\Fonts\seguiemj.ttf',
      r'C:\Windows\Fonts\segoeuib.ttf',
      '/System/Library/Fonts/Supplemental/Arial Bold.ttf',
      '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf',
    ]);
    _codeFontData = await _readFirstFont(const [
      r'C:\Windows\Fonts\consola.ttf',
      '/System/Library/Fonts/Menlo.ttc',
      '/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf',
    ]);
    _svgTextFontData = await _readFirstFont(const [
      r'C:\Windows\Fonts\segoeui.ttf',
      '/System/Library/Fonts/Supplemental/Arial Unicode.ttf',
      '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf',
    ]);
  }

  Future<List<int>?> _readFirstFont(List<String> paths) async {
    for (final path in paths) {
      final file = File(path);
      if (await file.exists()) return file.readAsBytes();
    }
    return null;
  }

  Future<void> _loadSvgTextFont() {
    return _svgTextFontLoad ??= () async {
      final fontData = _svgTextFontData;
      if (fontData == null) return;
      await loadFontFromList(
        Uint8List.fromList(fontData),
        fontFamily: _svgTextFontFamily,
      );
    }();
  }

  PdfFont _font(
    double size, {
    bool bold = false,
    bool monospace = false,
  }) {
    final data = monospace
        ? _codeFontData
        : bold
            ? _boldFontData ?? _regularFontData
            : _regularFontData;
    if (data != null) return PdfTrueTypeFont(data, size);

    return PdfStandardFont(
      monospace ? PdfFontFamily.courier : PdfFontFamily.helvetica,
      size,
      style: bold ? PdfFontStyle.bold : PdfFontStyle.regular,
    );
  }

  String _pdfSafeText(String text) {
    final safe = StringBuffer();
    for (final rune in text.runes) {
      if (rune >= 0xD800 && rune <= 0xDFFF) {
        // A standalone UTF-16 surrogate is malformed text. Preserve valid
        // emoji (which are supplementary-plane code points) and guard only
        // this invalid input so it cannot break PDF generation.
        safe.write('?');
      } else {
        safe.writeCharCode(rune);
      }
    }
    return safe.toString();
  }

  String _cleanText(String text) => _sanitizeExportText(text)
      .replaceAll(RegExp(r'[ \t]+'), ' ')
      .replaceAll(RegExp(r'\n{3,}'), '\n\n')
      .trim();

  String _sanitizeExportText(String text) {
    return _decodeHtmlEntities(text)
        .replaceAll(r'\"', '"')
        .replaceAll(r"\'", "'")
        .replaceAll(r'\/', '/')
        // A few providers leak a closing Markdown table delimiter and JSON
        // quote sequence into prose after a URL, for example: `.../ |\"\"\"`.
        // A proper Markdown table is parsed separately before it reaches here.
        .replaceAll(
          RegExp(r'[ \t]*\|(?:[ \t]*["\\]{0,3})?(?=(?:\r?\n|$))'),
          '',
        )
        // Markdown that starts correctly but is missing its opening marker
        // can leave a closing `**` at the end of a label. Valid bold spans are
        // parsed before this sanitizer runs, so only this dangling suffix is
        // removed.
        .replaceAll(
          RegExp(r'\*{2,}(?=(?:[ \t]*\r?\n|[ \t]*$))'),
          '',
        );
  }

  String _decodeHtmlEntities(String text) {
    var decoded = text;
    // The same text can travel through several JSON/HTML layers before it
    // reaches the exporter. A generous cap prevents pathological input from
    // looping forever while still fully decoding normal provider output.
    for (var pass = 0; pass < 32; pass++) {
      final next = decoded
          .replaceAll(RegExp(r'&amp;', caseSensitive: false), '&')
          .replaceAll(RegExp(r'&quot;', caseSensitive: false), '"')
          .replaceAll(RegExp(r'&apos;', caseSensitive: false), "'")
          .replaceAll(RegExp(r'&nbsp;', caseSensitive: false), ' ')
          .replaceAll(RegExp(r'&lt;', caseSensitive: false), '<')
          .replaceAll(RegExp(r'&gt;', caseSensitive: false), '>')
          .replaceAllMapped(
        RegExp(r'&#(x[0-9a-fA-F]+|[0-9]+);'),
        (match) {
          final rawCode = match.group(1)!;
          final isHex = rawCode.startsWith('x');
          final codePoint = int.tryParse(
            isHex ? rawCode.substring(1) : rawCode,
            radix: isHex ? 16 : 10,
          );
          if (codePoint == null ||
              codePoint <= 0 ||
              codePoint > 0x10FFFF ||
              (codePoint >= 0xD800 && codePoint <= 0xDFFF)) {
            return '?';
          }
          return String.fromCharCode(codePoint);
        },
      );
      if (next == decoded) return decoded;
      decoded = next;
    }
    return decoded;
  }

  /// Some model providers serialize a whole Markdown reply as one escaped
  /// string. Convert only that no-real-newline shape before parsing so its
  /// headings, rules, and emphasis still become formatted PDF content.
  String _normalizeMarkdownSource(String source) {
    if (source.contains('\n') || !source.contains(r'\n')) return source;
    return source.replaceAll(r'\r\n', '\n').replaceAll(r'\n', '\n');
  }

  /// A model occasionally puts a complete formatted answer in a Markdown or
  /// YAML-labelled fence. Preserve actual data/code fences, but render a
  /// clearly Markdown-shaped document instead of printing its `###` and
  /// `***` tokens verbatim.
  bool _looksLikeWrappedMarkdown(String source) {
    var markdownSignals = 0;
    for (final rawLine in source.split('\n')) {
      final line = rawLine.trim();
      if (line.isEmpty) continue;
      if (RegExp(r'^#{1,6}\s+\S').hasMatch(line)) {
        markdownSignals += 3;
      } else if (RegExp(r'^(?:\*{3,}|-{3,}|_{3,})$').hasMatch(line)) {
        markdownSignals += 2;
      } else if (RegExp(r'^(?:[-+*]|\d+\.)\s+\S').hasMatch(line)) {
        markdownSignals += 2;
      } else if (line.startsWith('> ')) {
        markdownSignals += 2;
      } else if (RegExp(r'\*\*[^*]+\*\*').hasMatch(line)) {
        markdownSignals++;
      }
      if (markdownSignals >= 4) return true;
    }
    return false;
  }

  bool _shouldRenderCodeBlockAsMarkdown(
    markdown.Element pre,
    String source,
  ) {
    final language = _codeFenceLanguage(pre);
    if (language == 'markdown' || language == 'md') return true;
    if (language == 'yaml' || language == 'yml') {
      return _containsMarkdownSyntax(source);
    }
    return _looksLikeWrappedMarkdown(source);
  }

  bool _containsMarkdownSyntax(String source) {
    return RegExp(r'^#{1,6}\s+\S', multiLine: true).hasMatch(source) ||
        RegExp(r'\*\*[^*\n]+\*\*').hasMatch(source);
  }

  String? _codeFenceLanguage(markdown.Element pre) {
    final codeElement = (pre.children ?? const <markdown.Node>[])
        .whereType<markdown.Element>()
        .firstWhere(
          (element) => element.tag == 'code',
          orElse: () => markdown.Element('', <markdown.Node>[]),
        );
    final className = codeElement.attributes['class']?.toLowerCase() ?? '';
    final match = RegExp(r'(?:^|\s)language-([^\s]+)').firstMatch(className);
    return match?.group(1);
  }

  String _formatDate(DateTime time) {
    final local = time.toLocal();
    return '${local.year.toString().padLeft(4, '0')}-'
        '${local.month.toString().padLeft(2, '0')}-'
        '${local.day.toString().padLeft(2, '0')} '
        '${local.hour.toString().padLeft(2, '0')}:'
        '${local.minute.toString().padLeft(2, '0')}';
  }
}

/// Text-only documents use a worker isolate so a long assistant response does
/// not monopolize the Flutter UI thread while it is being laid out.
Future<List<int>> _buildTextOnlyPdfInBackground(
  String source,
  String title,
) async {
  final renderer = MarkdownPdfService();
  await renderer._loadFonts();
  return renderer._buildPdfBytes(source, title);
}

class _PdfInlineText {
  final String text;
  final bool bold;

  const _PdfInlineText(this.text, {this.bold = false});
}

class _MermaidEdge {
  final String from;
  final String to;

  const _MermaidEdge(this.from, this.to);
}

class _PdfCursor {
  _PdfCursor(this.document, this.page);

  final PdfDocument document;
  PdfPage page;
  double y = _pdfMargin;

  double get width => page.getClientSize().width - (_pdfMargin * 2);
  double get _bottom => page.getClientSize().height - _pdfMargin;

  PdfLayoutFormat get layoutFormat => PdfLayoutFormat(
        layoutType: PdfLayoutType.paginate,
        paginateBounds: Rect.fromLTWH(
          _pdfMargin,
          _pdfMargin,
          width,
          _bottom - _pdfMargin,
        ),
      );

  void ensureSpace(double amount) {
    if (y + amount <= _bottom) return;
    page = document.pages.add();
    y = _pdfMargin;
  }

  void updateFrom(PdfLayoutResult result, {required double bottomSpacing}) {
    page = result.page;
    y = result.bounds.bottom + bottomSpacing;
    ensureSpace(1);
  }
}

class MarkdownPdfException implements Exception {
  final String message;

  const MarkdownPdfException(this.message);

  @override
  String toString() => message;
}
